# copied from roles/geerlingguy.adminer/tasks/main.yml#L23

- name: Set the proper Apache configuration directory (Debian).
  set_fact:
    apache_extra_conf_dir: "{{ 'conf-enabled' if apache_vhosts_version == '2.4' else 'conf.d' }}"
  when: ansible_os_family == 'Debian'

- name: Add Apache configuration file for Adminer (Debian).
  template:
    src: adminer.conf.j2
    dest: "{{ apache_conf_path }}/{{ apache_extra_conf_dir }}/adminer.conf"
  when: ansible_os_family == 'Debian'
  notify: restart apache

- name: Add Apache configuration file for Adminer (RedHat).
  template:
    src: adminer.conf.j2
    dest: "{{ apache_conf_path }}/adminer.conf"
  when: ansible_os_family == 'RedHat'
  notify: restart apache
